# Generated by Django 3.2.3 on 2021-05-24 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realstateco_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='properties', to='realstateco_api.owner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
